# Site settings
title: Mark Cutter - Purple Hat Psychology
email: mark@innovationinsociety.com
url: https://apothecarymark.github.io/purplehat
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "counselling psychology, psychotherapy, coaching"
skills: "Trainee Counselling Psychologist - Integrative Psychotherapist - Coach"
meta_author: Cutter Mark

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80439f #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 5C366F #FD6E8A
  secondary-dark: 301934 #A2122F
  tertiary: BE81DC

# Footer settings
footer:
  copyright: Mark Cutter
  location: Location
  social: Around the Web
  credits: Email Me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Lancaster, UK
  - line: London, UK

# Credits content
credits: "Email mark@innovationinsociety.com if you'd like to talk more."

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

prose:
  metadata:
    _includes:
      - name: "title"
        field:
          element: "hidden"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
    contact.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/contact"
    about.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/about"
    _posts:
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
      - name: "categories"
        field:
          element: "hidden"
          label: "categories"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
  media: "img"
  ignore:
    - /.github
    - /_includes
    - /_layouts
    - /css
    - /js
    - /img
    - /mail
    - /css
    - /categories
    - CNAME
    - Rakefile
    - sitemap.xml
    - feed.xml
    - .travis.yml
    - screenshot.png
    - style.css
    - readme.html
    - README.md
    - .gitignore
    - robots.txt
    - 404.html
    - index.html
    - Gemfile
    - Gemfile.lock
    - LICENCE
    - freelancer-theme-jekyll.gemspec