# Site settings
title: Mark Cutter
email: mark@innovationinsociety.com
url: "https://maninthepurplehat.com"
baseurl: ""
description: "Mark Cutter AKA the Man in the Purple Hat: Executive Coach, ADHD Coach and Disability Specialist. An expert in accessible transport and disability hate crime, providing consulantcy services, coaching psychology, executive coaching and ADHD coaching. A disability advocate currently training in Counselling Psychology and Psychotherapy." # continuous prose description, can be seen by web crawlers but not by humans
keywords: "counselling psychology, psychotherapy, coaching, disability, neurodiversity, financial trauma, adhd coach" # comma-separated keyword list, can be seen by web crawlers but not by humans
skills: "The Man in the Purple Hat - Executive Coach, ADHD Coach and Disability Specialist" # text shown in subtitle area of top section, human-readable
meta_author: Cutter Mark
about_title: "Why are we here?"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80439f #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 5C366F #FD6E8A
  secondary-dark: 301934 #A2122F
  tertiary: BE81DC

# Footer settings
footer:
  copyright: Mark Cutter
  location: Professional Registration
  social: Around the Web
  credits: Email Me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/themarkcutter
  - title: linkedin
    url: https://www.linkedin.com/in/markcutter  
  - title: tiktok
    url: https://www.tiktok.com/@the.man.in.the.pu
  - title: buy_me_a_coffee
    url: https://buymeacoffee.com/maninthepurplehat

# Postal address (add as many lines as necessary)
address:
  - line: "British Psychological Association:" 
  - line: "GMBPsS"
  - line: "(registration number: 532729)" 
  - line: ""
  - line: "UK Council for Psychotherapy (UKCP):"
  - line: "Trainee Member"
  - line: "(registration number: 2011188374)"

# Credits content
credits: "mark@maninthepurplehat.com"

# Build settings
markdown: kramdown
permalink: pretty

#for posts
# defaults:
#  - scope:
#      # path: ""
#      type: "posts"
#    values:
#      permalink: /blog/

#collections
collections:
 about:
   sort_by: order

prose:
  metadata:
    _includes:
      - name: "title"
        field:
          element: "hidden"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
    contact.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/contact"
    about.md:
      - name: "subtitle"
        field:
          element: "text"
          label: "subtitle"
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/about"
    _posts:
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "img"
        field:
          element: "image"
          label: "featured image"
      - name: "alt"
        field:
          element: "text"
          label: "image alt text"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
      - name: "category"
        field:
          element: "text"
          label: "category"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
  media: "img"
  ignore:
    - /.github
    - /_includes
    - /_layouts
    - /css
    - /js
    - /mail
    - /css
    - /categories
    - CNAME
    - Rakefile
    - sitemap.xml
    - feed.xml
    - .travis.yml
    - screenshot.png
    - style.css
    - readme.html
    - README.md
    - .gitignore
    - robots.txt
    - 404.html
    - index.html
    - Gemfile
    - Gemfile.lock
    - LICENCE
    - freelancer-theme-jekyll.gemspec
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico
    - mstile-150x150.png
    - safari-pinned-tab.svg
    - site.webmanifest
